version: '3.8'

services:
  auth-app:
    build: .
    container_name: auth-app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
     - ./:/app
     - /app/node_modules
    depends_on:
      - auth-db

  auth-db:
    image: mysql
    container_name: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=mohammad
      - MYSQL_DATABASE=auth
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: